all: challenge5 challenge11 challenge12 challenge13 challenge14

challenge5: challenge5.c
	gcc -o challenge5 challenge5.c

challenge11: challenge11.c
	gcc -o challenge11 challenge11.c

challenge12: challenge12.c
	gcc -o challenge12 challenge12.c

challenge13: challenge13.c
	gcc -o challenge13 challenge13.c

challenge14: challenge14.c
	gcc -o challenge14 challenge14.c

clean:
	rm challenge5 challenge11 challenge12 challenge13 challenge14
